# Generated by Django 5.1.6 on 2025-02-26 21:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='type',
            new_name='direction',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='id',
        ),
        migrations.AddField(
            model_name='conversation',
            name='conversation_id',
            field=models.TextField(default='SENT', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversation',
            name='end_conversation_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='start_conversation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='conversation_id',
            field=models.ForeignKey(default='1111111111111', on_delete=django.db.models.deletion.CASCADE, to='conversations.conversation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='message_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
